version: '4'
services:
  www:
    image: php:apache
    volumes:
      - "../css:/var/www/html/css"
      - "../html:/var/www/html/html"
      - "../image:/var/www/html/image"
      - "../three:/var/www/html/three"
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
    - PMA_HOST=db
    - PMA_PORT=3306